options:
  fqdn:
    type: string
    default: localhost
    description: FQDN of the server
  update-tasks:
    type: int
    default: 2
    description: number of feed update tasks to spawn
  update-interval:
    type: int
    default: 300
    description: frequency to check for feed updates
