#!/bin/bash

set -e

timestamp=`date +%s`

juju-log "Upgrading tt-rss"

juju-log "Stopping apache and feed update daemon"

hooks/stop

juju-log "Moving old tt-rss installation to /tmp/tt-rss-old"

mv /var/www/tt-rss /tmp/tt-rss-${timestamp}

juju-log "Performing upgrade"

hooks/install

juju-log "Migration old config settings to new installation"

cp /tmp/tt-rss-${timestamp}/config.php /var/www/tt-rss/config.php
chown www-data: /var/www/tt-rss/config.php

juju-log "Updating and starting services"

hooks/config-changed
